// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: proto/random-number.proto

package random_number

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMessage) Reset() {
	*x = ReqMessage{}
	mi := &file_proto_random_number_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMessage) ProtoMessage() {}

func (x *ReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_random_number_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMessage.ProtoReflect.Descriptor instead.
func (*ReqMessage) Descriptor() ([]byte, []int) {
	return file_proto_random_number_proto_rawDescGZIP(), []int{0}
}

func (x *ReqMessage) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type ResMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RandNum       int64                  `protobuf:"varint,1,opt,name=randNum,proto3" json:"randNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResMessage) Reset() {
	*x = ResMessage{}
	mi := &file_proto_random_number_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMessage) ProtoMessage() {}

func (x *ResMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_random_number_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMessage.ProtoReflect.Descriptor instead.
func (*ResMessage) Descriptor() ([]byte, []int) {
	return file_proto_random_number_proto_rawDescGZIP(), []int{1}
}

func (x *ResMessage) GetRandNum() int64 {
	if x != nil {
		return x.RandNum
	}
	return 0
}

var File_proto_random_number_proto protoreflect.FileDescriptor

const file_proto_random_number_proto_rawDesc = "" +
	"\n" +
	"\x19proto/random-number.proto\x12\x02rn\"\"\n" +
	"\n" +
	"ReqMessage\x12\x14\n" +
	"\x05reqId\x18\x01 \x01(\tR\x05reqId\"&\n" +
	"\n" +
	"ResMessage\x12\x18\n" +
	"\arandNum\x18\x01 \x01(\x03R\arandNum2C\n" +
	"\fRandomNumber\x123\n" +
	"\x0fGetRandomNumber\x12\x0e.rn.ReqMessage\x1a\x0e.rn.ResMessage\"\x00B\x11Z\x0f./random-numberb\x06proto3"

var (
	file_proto_random_number_proto_rawDescOnce sync.Once
	file_proto_random_number_proto_rawDescData []byte
)

func file_proto_random_number_proto_rawDescGZIP() []byte {
	file_proto_random_number_proto_rawDescOnce.Do(func() {
		file_proto_random_number_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_random_number_proto_rawDesc), len(file_proto_random_number_proto_rawDesc)))
	})
	return file_proto_random_number_proto_rawDescData
}

var file_proto_random_number_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_random_number_proto_goTypes = []any{
	(*ReqMessage)(nil), // 0: rn.ReqMessage
	(*ResMessage)(nil), // 1: rn.ResMessage
}
var file_proto_random_number_proto_depIdxs = []int32{
	0, // 0: rn.RandomNumber.GetRandomNumber:input_type -> rn.ReqMessage
	1, // 1: rn.RandomNumber.GetRandomNumber:output_type -> rn.ResMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_random_number_proto_init() }
func file_proto_random_number_proto_init() {
	if File_proto_random_number_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_random_number_proto_rawDesc), len(file_proto_random_number_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_random_number_proto_goTypes,
		DependencyIndexes: file_proto_random_number_proto_depIdxs,
		MessageInfos:      file_proto_random_number_proto_msgTypes,
	}.Build()
	File_proto_random_number_proto = out.File
	file_proto_random_number_proto_goTypes = nil
	file_proto_random_number_proto_depIdxs = nil
}
