// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: packages/random-number/random-number.proto

package random_number

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RandomNumber_GetRandomNumber_FullMethodName = "/rn.RandomNumber/GetRandomNumber"
)

// RandomNumberClient is the client API for RandomNumber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RandomNumberClient interface {
	GetRandomNumber(ctx context.Context, in *ReqMessage, opts ...grpc.CallOption) (*ResMessage, error)
}

type randomNumberClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomNumberClient(cc grpc.ClientConnInterface) RandomNumberClient {
	return &randomNumberClient{cc}
}

func (c *randomNumberClient) GetRandomNumber(ctx context.Context, in *ReqMessage, opts ...grpc.CallOption) (*ResMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResMessage)
	err := c.cc.Invoke(ctx, RandomNumber_GetRandomNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomNumberServer is the server API for RandomNumber service.
// All implementations must embed UnimplementedRandomNumberServer
// for forward compatibility.
type RandomNumberServer interface {
	GetRandomNumber(context.Context, *ReqMessage) (*ResMessage, error)
	mustEmbedUnimplementedRandomNumberServer()
}

// UnimplementedRandomNumberServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRandomNumberServer struct{}

func (UnimplementedRandomNumberServer) GetRandomNumber(context.Context, *ReqMessage) (*ResMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomNumber not implemented")
}
func (UnimplementedRandomNumberServer) mustEmbedUnimplementedRandomNumberServer() {}
func (UnimplementedRandomNumberServer) testEmbeddedByValue()                      {}

// UnsafeRandomNumberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandomNumberServer will
// result in compilation errors.
type UnsafeRandomNumberServer interface {
	mustEmbedUnimplementedRandomNumberServer()
}

func RegisterRandomNumberServer(s grpc.ServiceRegistrar, srv RandomNumberServer) {
	// If the following call pancis, it indicates UnimplementedRandomNumberServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RandomNumber_ServiceDesc, srv)
}

func _RandomNumber_GetRandomNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomNumberServer).GetRandomNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RandomNumber_GetRandomNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomNumberServer).GetRandomNumber(ctx, req.(*ReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RandomNumber_ServiceDesc is the grpc.ServiceDesc for RandomNumber service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RandomNumber_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rn.RandomNumber",
	HandlerType: (*RandomNumberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomNumber",
			Handler:    _RandomNumber_GetRandomNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "packages/random-number/random-number.proto",
}
