// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: packages/renderer/renderer.proto

package renderer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         string                 `protobuf:"bytes,1,opt,name=reqId,proto3" json:"reqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_packages_renderer_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_packages_renderer_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_packages_renderer_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type ReqMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqMessage) Reset() {
	*x = ReqMessage{}
	mi := &file_packages_renderer_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqMessage) ProtoMessage() {}

func (x *ReqMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packages_renderer_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqMessage.ProtoReflect.Descriptor instead.
func (*ReqMessage) Descriptor() ([]byte, []int) {
	return file_packages_renderer_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *ReqMessage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ReqMessage) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ResMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markup        string                 `protobuf:"bytes,1,opt,name=markup,proto3" json:"markup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResMessage) Reset() {
	*x = ResMessage{}
	mi := &file_packages_renderer_renderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResMessage) ProtoMessage() {}

func (x *ResMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packages_renderer_renderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResMessage.ProtoReflect.Descriptor instead.
func (*ResMessage) Descriptor() ([]byte, []int) {
	return file_packages_renderer_renderer_proto_rawDescGZIP(), []int{2}
}

func (x *ResMessage) GetMarkup() string {
	if x != nil {
		return x.Markup
	}
	return ""
}

var File_packages_renderer_renderer_proto protoreflect.FileDescriptor

const file_packages_renderer_renderer_proto_rawDesc = "" +
	"\n" +
	" packages/renderer/renderer.proto\x12\brenderer\" \n" +
	"\bMetadata\x12\x14\n" +
	"\x05reqId\x18\x01 \x01(\tR\x05reqId\"P\n" +
	"\n" +
	"ReqMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12.\n" +
	"\bmetadata\x18\x02 \x01(\v2\x12.renderer.MetadataR\bmetadata\"$\n" +
	"\n" +
	"ResMessage\x12\x16\n" +
	"\x06markup\x18\x01 \x01(\tR\x06markup2M\n" +
	"\x0fRenderingEngine\x12:\n" +
	"\n" +
	"RenderPage\x12\x14.renderer.ReqMessage\x1a\x14.renderer.ResMessage\"\x00B\fZ\n" +
	"./rendererb\x06proto3"

var (
	file_packages_renderer_renderer_proto_rawDescOnce sync.Once
	file_packages_renderer_renderer_proto_rawDescData []byte
)

func file_packages_renderer_renderer_proto_rawDescGZIP() []byte {
	file_packages_renderer_renderer_proto_rawDescOnce.Do(func() {
		file_packages_renderer_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_renderer_renderer_proto_rawDesc), len(file_packages_renderer_renderer_proto_rawDesc)))
	})
	return file_packages_renderer_renderer_proto_rawDescData
}

var file_packages_renderer_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_packages_renderer_renderer_proto_goTypes = []any{
	(*Metadata)(nil),   // 0: renderer.Metadata
	(*ReqMessage)(nil), // 1: renderer.ReqMessage
	(*ResMessage)(nil), // 2: renderer.ResMessage
}
var file_packages_renderer_renderer_proto_depIdxs = []int32{
	0, // 0: renderer.ReqMessage.metadata:type_name -> renderer.Metadata
	1, // 1: renderer.RenderingEngine.RenderPage:input_type -> renderer.ReqMessage
	2, // 2: renderer.RenderingEngine.RenderPage:output_type -> renderer.ResMessage
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_packages_renderer_renderer_proto_init() }
func file_packages_renderer_renderer_proto_init() {
	if File_packages_renderer_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_renderer_renderer_proto_rawDesc), len(file_packages_renderer_renderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_renderer_renderer_proto_goTypes,
		DependencyIndexes: file_packages_renderer_renderer_proto_depIdxs,
		MessageInfos:      file_packages_renderer_renderer_proto_msgTypes,
	}.Build()
	File_packages_renderer_renderer_proto = out.File
	file_packages_renderer_renderer_proto_goTypes = nil
	file_packages_renderer_renderer_proto_depIdxs = nil
}
