// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/renderer.proto

package renderer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RenderingEngine_RenderPage_FullMethodName = "/renderer.RenderingEngine/RenderPage"
)

// RenderingEngineClient is the client API for RenderingEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RenderingEngineClient interface {
	RenderPage(ctx context.Context, in *ReqMessage, opts ...grpc.CallOption) (*ResMessage, error)
}

type renderingEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewRenderingEngineClient(cc grpc.ClientConnInterface) RenderingEngineClient {
	return &renderingEngineClient{cc}
}

func (c *renderingEngineClient) RenderPage(ctx context.Context, in *ReqMessage, opts ...grpc.CallOption) (*ResMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResMessage)
	err := c.cc.Invoke(ctx, RenderingEngine_RenderPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RenderingEngineServer is the server API for RenderingEngine service.
// All implementations must embed UnimplementedRenderingEngineServer
// for forward compatibility.
type RenderingEngineServer interface {
	RenderPage(context.Context, *ReqMessage) (*ResMessage, error)
	mustEmbedUnimplementedRenderingEngineServer()
}

// UnimplementedRenderingEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRenderingEngineServer struct{}

func (UnimplementedRenderingEngineServer) RenderPage(context.Context, *ReqMessage) (*ResMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenderPage not implemented")
}
func (UnimplementedRenderingEngineServer) mustEmbedUnimplementedRenderingEngineServer() {}
func (UnimplementedRenderingEngineServer) testEmbeddedByValue()                         {}

// UnsafeRenderingEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RenderingEngineServer will
// result in compilation errors.
type UnsafeRenderingEngineServer interface {
	mustEmbedUnimplementedRenderingEngineServer()
}

func RegisterRenderingEngineServer(s grpc.ServiceRegistrar, srv RenderingEngineServer) {
	// If the following call pancis, it indicates UnimplementedRenderingEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RenderingEngine_ServiceDesc, srv)
}

func _RenderingEngine_RenderPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RenderingEngineServer).RenderPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RenderingEngine_RenderPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RenderingEngineServer).RenderPage(ctx, req.(*ReqMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RenderingEngine_ServiceDesc is the grpc.ServiceDesc for RenderingEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RenderingEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "renderer.RenderingEngine",
	HandlerType: (*RenderingEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderPage",
			Handler:    _RenderingEngine_RenderPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/renderer.proto",
}
